#spring:
#  application:
#    name: usercenter
#eureka:
#  instance:
#    preferIpAddress: true
#    instance-id: 168.130.6.55:8081
#  client:
#    serviceUrl:
#      defaultZone: http://10.33.1.160:8082/eureka/
#      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://192.168.211.1:8761/eureka/
#      defaultZone: http://${janloong.eureka.ip}:8761/eureka
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"

dooo:
  #    custom: asd
  custom: ${janloong.eureka.ip}