server:
  port: 9001
spring:
  profiles:
    #    active: dev
    active: home
  application:
    name: spring-security
  datasource:
    #    url:  "jdbc:mysql://127.0.0.1:3306/spring-sec?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
    #    url:  "jdbc:mysql://192.168.211.129:3306/spring-sec?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    username: root
    #    password: root
    url:  "jdbc:mysql://47.99.123.251:3306/spring-sec?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true"
    username: config.file= classpath:../../../../../../auth.yml
    password: config.file= classpath:../../../../../../auth.yml
  #  thymeleaf:
  #    check-template-location: true
  #    check-template: true
  #    cache: false
  #    mode: LEGACYHTML5
  #    prefix: classpath:/static/
  #    suffix: .html
  #    enabled: true
  #  datasource:
  #    url:  "jdbc:h2:~/test"
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:
  #  h2:
  #    console:
  #      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #    virtual-host: /
#    template:
#      mandatory: true
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated #必须配置这个才会确认回调
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    listener:
      type: simple
      simple:
#        acknowledge-mode: manual #手动确认
        acknowledge-mode: auto #自动
        prefetch: 1 #限制每次发送一条数据。
        concurrency: 3 #同一个队列启动几个消费者
        max-concurrency: 3 #启动消费者最大数量
        #重试策略配置
        retry:
          enabled: false #是否支持重试
          multiplier: 1.5  #时间策略重试因子
          max-attempts: 3
          max-interval: 10000  #最大重试间隔
          initial-interval: 2000  #重试间隔
        default-requeue-rejected: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

#debug: true
logging:
  level:
    com.janloong: DEBUG
doo:
  security:
    code:
      image:
        url: '/login'