server:
  port: 9001
spring:
  profiles:
    #    active: dev
    active: home
  application:
    name: spring-security
  datasource:
    #    url:  "jdbc:mysql://127.0.0.1:3306/spring-sec?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
    #    url:  "jdbc:mysql://192.168.211.129:3306/spring-sec?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    username: root
    #    password: root
    url:  "jdbc:mysql://47.99.123.251:3306/spring-sec?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true"
    username: config.file= classpath:../../../../../../auth.yml
    password: config.file= classpath:../../../../../../auth.yml
  #  thymeleaf:
  #    check-template-location: true
  #    check-template: true
  #    cache: false
  #    mode: LEGACYHTML5
  #    prefix: classpath:/static/
  #    suffix: .html
  #    enabled: true
  #  datasource:
  #    url:  "jdbc:h2:~/test"
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:
  #  h2:
  #    console:
  #      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"

#debug: true
logging:
  level:
    com.janloong: DEBUG
doo:
  security:
    code:
      image:
        url: '/login'