server:
  port: 9001
spring:
  application:
    name: spring-security
  datasource:
    url:  "jdbc:mysql://127.0.0.1:3306/spring-sec?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  thymeleaf:
    check-template-location: true
    check-template: true
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/static/
    suffix: .html
    enabled: true
  #  datasource:
  #    url:  "jdbc:h2:~/test"
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:
  #  h2:
  #    console:
  #      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#debug: true
logging:
  level:
    com.janloong: DEBUG