spring:
  zipkin:
    #    baseUrl: http://localhost:9411
    #    sender:
    #        type: rabbits
    service:
      name: ${spring.application.name}
    message-timeout: 5
  sleuth:
    sampler:
      probability: 0.5f
  cloud:
    config:
      label: master
      profile: test
      #   uri: http://localhost:8888/   # 加入eureka服务后可以直接配置服务名
      discovery:
        enabled: true
        serviceId: config-server
      name: ${spring.application.name},common
    bus:
      trace:
        enabled: true
  rabbitmq:
    port: ${janloong.rabbitmq.port}
    host: ${janloong.rabbitmq.ip}
    username: ${janloong.rabbitmq.username}
    password: ${janloong.rabbitmq.password}
eureka:
  instance:
    #    preferIpAddress: true
    #      instance-id: ${janloong.eureka.ip}:${server.port}
    #    instance-id: 127.0.0.1:8762
    appname: ${spring.application.name}
  client:
    service-url:
      #      defaultZone: http://${janloong.eureka.ip}:${janloong.eureka.port}/eureka,${janloong.eureka.other-urls}
      defaultZone: http://127.0.0.1:8762/eureka