spring:
  cloud:
    gateway:
      routes:
      - id: provide1
        uri: http://localhost:8081
        predicates:
        - path: /test
        - weigth: provide,90
      - id: provide2
        uri: http://localhost:8082
        predicates:
        - path: /test
        - weigth: provide,10
