
eureka:
#  instance:
#    prefer-ip-address: true
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuul
server:
  port: 8767

zuul:
  routes:
    rout-1:
      path: /rout-1/**
      serviceId: custom-1
    rout-2:
      path: /rout-2/**
      serviceId: custom-2

management:
  endpoints:
    web:
#      base-path: /
      exposure:
        include: "*"

info: #定义各种额外的详情给服务端显示
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"