FROM java:latest
MAINTAINER janloongdoo@gmail.com
ADD ss-zuul/target/zuul-0.0.1-SNAPSHOT.jar /root
WORKDIR /root
EXPOSE 8081
CMD ["java","-jar","zuul-0.0.1-SNAPSHOT.jar"]
#CMD ["nohup","java","-jar","ss-user-0.0.1-SNAPSHOT.jar","&"]
#CMD ["java","-version"]
