FROM java:latest
MAINTAINER janloongdoo@gmail.com
ADD eureka-server/target/eureka-server-0.0.1-SNAPSHOT.jar  /root
WORKDIR /root
EXPOSE 8761
#CMD ["nohup","java","-jar","eureka-server-0.0.1-SNAPSHOT.jar","&"," && "]
CMD ["java","-jar","eureka-server-0.0.1-SNAPSHOT.jar"]
