
eureka:
  client:
#  客户端多久从server端抓取一次服务注册信息
#    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8889/eureka/
spring:
  application:
    name: custom-1
  zipkin:
#    base-url: http://localhost:9411
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      probability: 0.5  #配置span的抽样分析比例
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 8765

management:
  endpoints:
      web:
        exposure:
          include: "*"

info: #定义各种额外的详情给服务端显示
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"

#自定义规则配置方式二
provide-1:
  ribbon:
    NFLoadBalancerRuleClassName: com.janloong.eurekaclient2.config.CustomRule
