#author:
#  name: janloong
#  domain: janloong
#  description: this is janloong
logging:
  level:
    com.janloong: debug
    web: debug
server:
  port: 8088
  ssl:
    key-store: classpath:keystore.p12
    key-alias: doo
    key-store-password: rzt123
    key-store-type: jks
