#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Copyright (c) 2018  All Rights Reserved.
# ProjectName: SpringCloud
# FileName: configClient-test.properties
# Author: janloongdoo@gmail.com
# Date: 18-10-12 \u4E0B\u53482:21
# LastModify: 18-10-12 \u4E0B\u53481:35
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

doo: janloong-test v 1.9
janloong:
  eureka:
    ip: 127.0.0.1
    port:
    urls:
  database:
    ip:
    port:
    url: