
#eureka:
#  instance:
#   客户端多久向server发送一次心跳
#    leaseRenewalIntervalInSeconds: 5
#   客户端多久未发送心跳，server 将其移除
#    leaseExpirationDurationInSeconds: 10
#    metadata-map:
#      company-name: crazyit
#  client:
# 客户端向服务端的响应时间
#    instanceInfoReplicationIntervalSeconds: 10
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
spring:
  application:
    name: provide-1
server:
  port: 8763
