server:
  port: 8081
spring:
  application:
    name: api-zuul
  profiles:
    #    active: dev
    active: prod
  http:
    encoding:
      charset: utf-8
security:
  oauth2:
    #    authorization:
    #      check-token-access:
    #      token-key-access:
    resource:
      #      id: zuul-doo
      #      service-id: authcenter
      #      token-info-uri: http://localhost:${server.port}/authcenter/oauth/check_token #网关地址负载认证中心服务
      token-info-uri: http://${janloong.authcenter.ip}:${server.port}/authcenter/oauth/check_token
      #网关地址负载认证中心服务
      #      prefer-token-info: true
      #      user-info-uri: http://localhost:${server.port}/authcenter/user
      prefer-token-info: true
    #      id: doo-credentials
    client:
      #      id: doo-zuul
      clientId: doo-zuul-id
      client-secret: secret-zuul
      user-authorization-uri: http://${janloong.authcenter.ip}:${server.port}/authcenter/oauth/authorize #网关地址负载认证中心服务
      access-token-uri: http://${janloong.authcenter.ip}:${server.port}/authcenter/oauth/token #网关地址负载认证中心服务
#  sessions: always
#proxy

management:
  endpoints:
    web:
      exposure:
        include: "*"

info: #定义各种额外的详情给服务端显示
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
