# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

#GET http://localhost:8080/setcache?name=a1
GET http://localhost:8080/setcache?name=a2
Accept: application/json

###
#GET http://localhost:8080/getcache?name=a1
GET http://localhost:8080/getcache?name=a2

###
GET http://localhost:8080/sign?name=doo&address=beijing

###
POST http://localhost:8082/actuator/shutdown

###
GET http://localhost:8082/wait

###
