# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

#添加用户
###
POST http://{{doo_host}}:{{doo_port}}/user/add
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8

{
  "username" : "doo",
  "password" : "doo",
  "roleId" : "program"
}


###
POST http://{{doo_host}}:{{doo_port}}/user/add
Content-Type: application/x-www-form-urlencoded

username=doo&password=doo&roleId=programer

###
GET http://{{doo_host}}/user/1
Cache-Control: no-cache
Accept: application/json

###查询所有的用户
GET http://{{doo_host}}/user
Cache-Control: no-cache
Accept: application/json

###
POST http://{{doo_host}}/login?username=doo&password=doo

###

GET http://{{doo_host}}/schedule/taskList

###
GET http://{{doo_host}}/schedule/start?taskKey=scheduledTask02

###
GET http://{{doo_host}}/schedule/restart?taskKey=scheduledTask01

###
GET http://{{doo_host}}/redis/addKey

###
GET http://{{doo_host}}/quartz/update

###
POST http://{{doo_host}}/quartz/add
Content-Type: application/x-www-form-urlencoded

#jobName=job3&jobGroup=group3&className=com.janloong.springsecurity.quartz.job.DooJob
type=2&jobName=job_simple2&jobGroup=group3&className=com.janloong.springsecurity.quartz.job.DooJob&date=2020-07-14 17:45:00

###
GET http://{{doo_host}}/quartz/pause?jobName=job3&jobGroup=group3
###
GET http://{{doo_host}}/quartz/resume?jobName=job3&jobGroup=group3

###
GET http://{{doo_host}}/quartz/list?jobName=job1&jobGroup=group1

###
GET http://{{doo_host}}/quartz/list

###
GET http://{{doo_host}}/quartz/remove?jobName=job2&jobGroup=group2
###
#GET http://{{doo_host}}/localDateTime/test?startTime=2020-01-11 15:22:20
POST http://{{doo_host}}/localDateTime/test
Content-Type: application/json

{
  "as": "asd",
  "startTime": "2019-12-13 00:00:00"
}

###
GET http://{{doo_host}}/request/info

### thread-test
GET http://{{doo_host}}//thread/test

###
