server:
  port: 9411
spring:
  application:
    name: zipkin-server

zipkin:
  collector:
    rabbitmq:
      addresses: localhost:5672
      password: guest
      username: guest
      queue: zipkin
