spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bingdg_1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
## springboot fileupload
#  http.multipart:
#    max-file-size: 128KB
#    max-request-size: 128KB
#
logging:
  level: info
