spring:
  profiles:
    active: client1
  rabbitmq:
    port: ${janloong.rabbitmq.port}
    host: ${janloong.rabbitmq.ip}
    username: ${janloong.rabbitmq.username}
    password: ${janloong.rabbitmq.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
from:
  config-server: ${janloong.eureka.ip}