#spring.application.name=config-client
#spring.cloud.config.label=master
#spring.cloud.config.profile=dev
#spring.cloud.config.uri= http://localhost:8888/
#server.port=8772
#spring:
#  config:
#    name: configClient
#spring:
#  profiles:
#    active: dev
server:
  port: 8893