logging:
  level:
    com.janloong: debug
    web: debug
#shiro配置
shiro:
  loginUrl: /loginUrl
  successUrl: /index
  sessionManager:
    # 将sessionId放入cookie中
    sessionIdCookieEnabled: true
    # 是否将sessionId放入Url地址栏中
    sessionIdUrlRewritingEnabled: true
  # 访问未授权页面时跳转页面
  unauthorizedUrl: /unauth
  web:
    # 开启shiro
    enabled: true
#server:
#  port: 8079