#构建自用的jre13环境
FROM ubuntu:18.04
#COPY jre /opt/jre
#ENV JAVA_HOME=/opt/jre CLASSPATH=/opt/jre/lib PATH=$PATH:/opt/jre/bin
#COPY jre8 /opt/jre8
#ENV JAVA_HOME=/opt/jre8 CLASSPATH=/opt/jre8/lib PATH=$PATH:/opt/jre8/bin
COPY jdk13 /opt/jdk13
ENV JAVA_HOME=/opt/jdk13 CLASSPATH=/opt/jdk13/lib PATH=$PATH:/opt/jdk13/bin
